spring.application.name=ei-core
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
server.servlet.context-path=/ei-core

spring.datasource.url=jdbc:postgresql://localhost:5432/ei_auth_db
spring.datasource.username= postgres
spring.datasource.password= postgres

spring.jpa.hibernate.ddl-auto= create
spring.jpa.show-sql= true

spring.liquibase.change-log= classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled= true

jwt.secret= myjwtsecretkey123456789
jwt.expirationMs= 3600000
