spring.application.name=ei-core
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/ei-core

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.tkdcbgeujuipfvrzxjnh.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:YOUR_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log= classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled= true
spring.liquibase.database-change-log-table= core_databasechangelog
spring.liquibase.database-change-log-lock-table= core_databasechangeloglock

jwt.secret=${JWT_SECRET:myjwtsecretkey123456789}
jwt.expirationMs=${JWT_EXPIRATION_MS:3600000}
