spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ei_auth_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

jwt:
  secret: myjwtsecretkey123456789
  expirationMs: 3600000