spring.application.name=ei-core
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/ei-core

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/extra_income_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:extra_income_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.liquibase.change-log= classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled= true
spring.liquibase.database-change-log-table= core_databasechangelog
spring.liquibase.database-change-log-lock-table= core_databasechangeloglock

jwt.secret=${JWT_SECRET:myjwtsecretkey123456789}
jwt.expirationMs=${JWT_EXPIRATION_MS:3600000}
